// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {Test} from "forge-std/Test.sol";
import {CovenantFacility} from "../src/CovenantFacility.sol";
import {INativeQueryVerifier, NativeQueryVerifierLib} from "../src/VerifierInterface.sol";
import {MockNativeQueryVerifier} from "./MockNativeQueryVerifier.sol";

// Evidence-path tests. The native verifier at 0x…0FD2 is replaced with a
// behavior-faithful double (vm.etch) so every test drives COVENANT's real production
// call surface: proof verification happens first, and all economic fields are decoded
// from the verified receipt bytes -- never taken from submitter input.
// Fixtures are generated by scripts/generate-fixtures.cjs using the official
// gluwa usc-sdk encoder (encoding.abiEncode) and its KeccakMerkleTree.
contract CovenantFacilityEvidenceTest is Test {
    CovenantFacility internal covenant;

    address internal lender = makeAddr("lender");
    address internal borrower = makeAddr("borrower");
    address internal outsider = makeAddr("outsider");

    string internal fixturesJson;

    // Fixture scenario keys (contracts/test/fixtures/fixtures.json).
    string internal constant VALID = "valid";
    string internal constant WRONG_EMITTER = "wrongEmitter";
    string internal constant WRONG_PAYER = "wrongPayer";
    string internal constant WRONG_RECIPIENT = "wrongRecipient";
    string internal constant WRONG_EVENT = "wrongEvent";
    string internal constant MALFORMED_LOG = "malformedLog";
    string internal constant REVERTED_TX = "revertedSourceTx";
    string internal constant PARTIAL_A = "partialA";
    string internal constant PARTIAL_B = "partialB";
    string internal constant MULTI_LOG = "multiLog";

    uint256 internal tranche = 20 ether;
    uint256 internal requiredUsdc;
    uint256 internal partialAUsdc;
    uint256 internal partialBUsdc;
    address internal usdc;

    function setUp() public {
        fixturesJson = vm.readFile("test/fixtures/fixtures.json");
        requiredUsdc = vm.parseJsonUint(fixturesJson, "$.meta.requiredAmount");
        partialAUsdc = vm.parseJsonUint(fixturesJson, "$.meta.partialAmounts[0]");
        partialBUsdc = vm.parseJsonUint(fixturesJson, "$.meta.partialAmounts[1]");
        usdc = vm.parseJsonAddress(fixturesJson, "$.meta.usdc");

        MockNativeQueryVerifier mockImpl = new MockNativeQueryVerifier();
        vm.etch(NativeQueryVerifierLib.PRECOMPILE_ADDRESS, address(mockImpl).code);
        covenant = new CovenantFacility();

        vm.deal(lender, 1_000 ether);
    }

    struct Scenario {
        bytes txBytes;
        uint64 chainKey;
        uint64 headerNumber;
        bytes32 root;
        bytes32[] siblingHashes;
        bool[] siblingIsLeft;
        bytes32 lowerEndpointDigest;
        bytes32[] roots;
    }

    function _load(string memory key) internal view returns (Scenario memory s) {
        string memory base = string.concat("$.scenarios.", key);
        s.txBytes = vm.parseJsonBytes(fixturesJson, string.concat(base, ".txBytes"));
        s.chainKey = uint64(vm.parseJsonUint(fixturesJson, string.concat(base, ".chainKey")));
        s.headerNumber = uint64(vm.parseJsonUint(fixturesJson, string.concat(base, ".headerNumber")));
        s.root = vm.parseJsonBytes32(fixturesJson, string.concat(base, ".merkleProof.root"));
        s.siblingHashes = vm.parseJsonBytes32Array(fixturesJson, string.concat(base, ".merkleProof.siblingHashes"));
        s.siblingIsLeft = vm.parseJsonBoolArray(fixturesJson, string.concat(base, ".merkleProof.siblingIsLeft"));
        s.lowerEndpointDigest =
            vm.parseJsonBytes32(fixturesJson, string.concat(base, ".continuityProof.lowerEndpointDigest"));
        s.roots = vm.parseJsonBytes32Array(fixturesJson, string.concat(base, ".continuityProof.roots"));
    }

    function _siblings(Scenario memory s)
        internal
        pure
        returns (INativeQueryVerifier.MerkleProofEntry[] memory entries)
    {
        entries = new INativeQueryVerifier.MerkleProofEntry[](s.siblingHashes.length);
        for (uint256 i; i < s.siblingHashes.length; ++i) {
            entries[i] = INativeQueryVerifier.MerkleProofEntry({hash: s.siblingHashes[i], isLeft: s.siblingIsLeft[i]});
        }
    }

    function _createAcceptedCovenant() internal returns (uint256 facilityId, uint256 covenantId) {
        Scenario memory s = _load(VALID);
        // COVENANT binds the covenant payer to the on-chain facility borrower.
        // The fixture payer therefore plays the borrower role here.
        address fixturePayer = vm.parseJsonAddress(fixturesJson, "$.meta.payer");
        vm.deal(fixturePayer, 1 ether);
        vm.prank(lender);
        facilityId = covenant.createFacility{value: 100 ether}(fixturePayer, tranche, uint64(block.number + 1_000));
        vm.prank(lender);
        covenantId = covenant.createCovenant(
            facilityId,
            s.chainKey,
            usdc,
            vm.parseJsonAddress(fixturesJson, "$.meta.recipient"),
            requiredUsdc,
            s.headerNumber - 50,
            s.headerNumber + 50,
            uint64(block.number + 500),
            0
        );
        vm.prank(fixturePayer);
        covenant.acceptCovenant(covenantId);
    }

    function _submit(uint256 covenantId, Scenario memory s) internal returns (bytes32 queryId, uint256 matched) {
        (queryId, matched) = covenant.submitEvidence(
            covenantId, s.chainKey, s.headerNumber, s.txBytes, s.root, _siblings(s), s.lowerEndpointDigest, s.roots
        );
    }

    /// @dev Replicates CovenantFacility._computeQueryId's 72-byte identity preimage.
    function _expectedQueryId(Scenario memory s) internal view returns (bytes32) {
        INativeQueryVerifier.MerkleProofEntry[] memory siblings = _siblings(s);
        uint64 txIndex = INativeQueryVerifier(NativeQueryVerifierLib.PRECOMPILE_ADDRESS).calculateTxIndex(
            INativeQueryVerifier.MerkleProof({root: bytes32(0), siblings: siblings})
        );
        uint64 chainKey = s.chainKey;
        uint64 height = s.headerNumber;
        bytes memory buf = new bytes(72);
        assembly {
            mstore(add(buf, 32), chainKey)
            mstore(add(buf, 64), shl(192, height))
            mstore(add(buf, 72), txIndex)
        }
        return keccak256(buf);
    }

    function test_FixtureTransferTopicMatchesContractConstant() public view {
        bytes32 fixtureTopic = vm.parseBytes32(vm.parseJsonString(fixturesJson, "$.meta.transferTopic"));
        assertEq(fixtureTopic, covenant.TRANSFER_EVENT_SIGNATURE());
    }

    function test_ValidVerifiedTransferSatisfiesCovenantAndUnlocksTranche() public {
        (uint256 facilityId, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);

        vm.expectEmit(true, true, true, true);
        emit CovenantFacility.EvidenceAccepted(
            covenantId, _expectedQueryId(s), s.headerNumber, requiredUsdc, requiredUsdc
        );
        vm.expectEmit(true, true, true, true);
        emit CovenantFacility.CovenantSatisfied(covenantId, facilityId, 40 ether);
        (bytes32 queryId, uint256 matched) = _submit(covenantId, s);

        assertEq(matched, requiredUsdc);
        assertTrue(covenant.processedQueries(queryId));
        assertEq(covenant.availableToDraw(facilityId), 40 ether);

        (,,,, uint256 unlocked,, uint256 activeCovenantId,, CovenantFacility.FacilityStatus facilityStatus) =
            covenant.facilities(facilityId);
        assertEq(unlocked, 40 ether);
        assertEq(activeCovenantId, 0);
        assertEq(uint256(facilityStatus), uint256(CovenantFacility.FacilityStatus.Active));

        (,,,,,, uint256 verifiedAmount,,,,, CovenantFacility.CovenantStatus covenantStatus) =
            covenant.covenants(covenantId);
        assertEq(verifiedAmount, requiredUsdc);
        assertEq(uint256(covenantStatus), uint256(CovenantFacility.CovenantStatus.Satisfied));
    }

    function test_EvidenceSubmissionIsPermissionless() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        vm.prank(outsider);
        (, uint256 matched) = _submit(covenantId, _load(VALID));
        assertEq(matched, requiredUsdc);
    }

    function test_InvalidMerkleProofRevertsAndDoesNotConsumeQuery() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory bad = _load(VALID);
        bad.siblingHashes[0] = bytes32(uint256(bad.siblingHashes[0]) ^ 1);

        vm.expectRevert(MockNativeQueryVerifier.InvalidMerkleProof.selector);
        _submit(covenantId, bad);
        assertFalse(covenant.processedQueries(_expectedQueryId(bad)));

        // A failed submission must not censor or consume the identity for a valid proof.
        (bytes32 goodId,) = _submit(covenantId, _load(VALID));
        assertTrue(covenant.processedQueries(goodId));
    }

    function test_VerifierRejectionReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);
        MockNativeQueryVerifier(NativeQueryVerifierLib.PRECOMPILE_ADDRESS).setFailNextVerify(true);
        vm.expectRevert(CovenantFacility.ProofVerificationFailed.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_CorruptedTransactionDataFailsVerification() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);
        s.txBytes[s.txBytes.length - 9] ^= 0x01;
        vm.expectRevert(MockNativeQueryVerifier.InvalidMerkleProof.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_WrongSourceChainReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);
        s.chainKey = s.chainKey + 1;
        vm.expectRevert(CovenantFacility.WrongSourceChain.selector);
        _submit(covenantId, s);
    }

    function test_SourceBlockOutsideWindowReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);
        s.headerNumber = s.headerNumber + 51;
        vm.expectRevert(CovenantFacility.SourceBlockOutsideWindow.selector);
        _submit(covenantId, s);
    }

    function test_WrongEmitterReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(WRONG_EMITTER);
        vm.expectRevert(CovenantFacility.NoMatchingPayment.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_WrongEventSignatureReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(WRONG_EVENT);
        vm.expectRevert(CovenantFacility.NoMatchingPayment.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_MalformedLogReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(MALFORMED_LOG);
        vm.expectRevert(CovenantFacility.NoMatchingPayment.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_RevertedSourceTransactionReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(REVERTED_TX);
        vm.expectRevert(CovenantFacility.SourceTransactionFailed.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_UnsupportedDecoderTypeRevertsBeforeDecoding() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(VALID);
        (, bytes[] memory chunks) = abi.decode(s.txBytes, (uint8, bytes[]));
        s.txBytes = abi.encode(uint8(9), chunks);

        // Bypass inclusion so the call reaches COVENANT's own decoder guard.
        MockNativeQueryVerifier(NativeQueryVerifierLib.PRECOMPILE_ADDRESS).setAcceptAny(true);
        vm.expectRevert(CovenantFacility.InvalidTerms.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_WrongPayerReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(WRONG_PAYER);
        vm.expectRevert(CovenantFacility.NoMatchingPayment.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    function test_WrongRecipientReverts() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(WRONG_RECIPIENT);
        vm.expectRevert(CovenantFacility.NoMatchingPayment.selector);
        _submit(covenantId, s);
        assertFalse(covenant.processedQueries(_expectedQueryId(s)));
    }

    /// @notice Decoder-ambiguity prosecution: one receipt with three Transfer logs —
    /// same-emitter/wrong-recipient, wrong-emitter/right-recipient, matching. Only the
    /// matching log counts; the others must not inflate verifiedAmount.
    function test_MultiLogReceiptCreditsOnlyMatchingTransfer() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(MULTI_LOG);
        (bytes32 queryId, uint256 matched) = _submit(covenantId, s);

        assertTrue(covenant.processedQueries(queryId));
        assertEq(matched, requiredUsdc); // exactly one log's worth, not three
        (,,,,,, uint256 verifiedAmount,,,,,) = covenant.covenants(covenantId);
        assertEq(verifiedAmount, requiredUsdc);
    }

    function test_PartialAmountsAccumulateUntilThreshold() public {
        (uint256 facilityId, uint256 covenantId) = _createAcceptedCovenant();

        (bytes32 idA, uint256 matchedA) = _submit(covenantId, _load(PARTIAL_A));
        assertTrue(covenant.processedQueries(idA));
        assertEq(matchedA, partialAUsdc);

        // Below threshold: covenant stays pending and no capital unlocks.
        (,,,, uint256 unlockedMid,,,,) = covenant.facilities(facilityId);
        assertEq(unlockedMid, tranche);
        (,,,,,,,,,,, CovenantFacility.CovenantStatus statusMid) = covenant.covenants(covenantId);
        assertEq(uint256(statusMid), uint256(CovenantFacility.CovenantStatus.Pending));

        (, uint256 matchedB) = _submit(covenantId, _load(PARTIAL_B));
        assertEq(matchedB, partialBUsdc);

        (,,,, uint256 unlockedEnd,,,,) = covenant.facilities(facilityId);
        assertEq(unlockedEnd, 2 * tranche);
        (,,,,,, uint256 verifiedTotal,,,,,) = covenant.covenants(covenantId);
        assertEq(verifiedTotal, partialAUsdc + partialBUsdc);
        assertGe(partialAUsdc + partialBUsdc, requiredUsdc);
    }

    function test_ReplayRejectedWhilePending() public {
        (, uint256 covenantId) = _createAcceptedCovenant();
        Scenario memory s = _load(PARTIAL_A);

        (bytes32 queryId,) = _submit(covenantId, s);
        assertTrue(covenant.processedQueries(queryId));

        // Same source transaction identity, covenant still pending: rejected as replay.
        vm.expectRevert(CovenantFacility.QueryAlreadyProcessed.selector);
        _submit(covenantId, s);
    }

    function test_ResubmissionAfterSatisfactionRejected() public {
        (uint256 facilityId, uint256 covenantId) = _createAcceptedCovenant();
        _submit(covenantId, _load(VALID));

        vm.expectRevert(CovenantFacility.CovenantNotPending.selector);
        _submit(covenantId, _load(VALID));

        // No double-unlock from either rejection path.
        (,,,, uint256 unlocked,,,,) = covenant.facilities(facilityId);
        assertEq(unlocked, 40 ether);
    }
}
